// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
)

const getAccountByAuthIdentity = `-- name: GetAccountByAuthIdentity :one
SELECT accounts.id, accounts.email
FROM accounts
JOIN auth_identities ON auth_identities.account_id = accounts.id
WHERE auth_identities.provider = $1 AND auth_identities.subject = $2
`

type GetAccountByAuthIdentityParams struct {
	Provider string
	Subject  string
}

type GetAccountByAuthIdentityRow struct {
	ID    string
	Email string
}

func (q *Queries) GetAccountByAuthIdentity(ctx context.Context, arg GetAccountByAuthIdentityParams) (GetAccountByAuthIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByAuthIdentity, arg.Provider, arg.Subject)
	var i GetAccountByAuthIdentityRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const getPlayerByAccountID = `-- name: GetPlayerByAccountID :one
SELECT id, account_id, display_name
FROM players
WHERE account_id = $1
`

type GetPlayerByAccountIDRow struct {
	ID          string
	AccountID   string
	DisplayName string
}

func (q *Queries) GetPlayerByAccountID(ctx context.Context, accountID string) (GetPlayerByAccountIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByAccountID, accountID)
	var i GetPlayerByAccountIDRow
	err := row.Scan(&i.ID, &i.AccountID, &i.DisplayName)
	return i, err
}
