// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO comments (id, round_id, jump_id, player_id, body, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateCommentParams struct {
	ID        string
	RoundID   string
	JumpID    sql.NullString
	PlayerID  string
	Body      string
	CreatedAt time.Time
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.ID,
		arg.RoundID,
		arg.JumpID,
		arg.PlayerID,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const listCommentsForJump = `-- name: ListCommentsForJump :many
SELECT id, round_id, jump_id, player_id, body, created_at
FROM comments
WHERE round_id = $1 AND jump_id = $2
ORDER BY created_at
`

type ListCommentsForJumpParams struct {
	RoundID string
	JumpID  sql.NullString
}

func (q *Queries) ListCommentsForJump(ctx context.Context, arg ListCommentsForJumpParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsForJump, arg.RoundID, arg.JumpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.JumpID,
			&i.PlayerID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsForRound = `-- name: ListCommentsForRound :many
SELECT id, round_id, player_id, body, created_at
FROM comments
WHERE round_id = $1 AND jump_id IS NULL
ORDER BY created_at
`

type ListCommentsForRoundRow struct {
	ID        string
	RoundID   string
	PlayerID  string
	Body      string
	CreatedAt time.Time
}

func (q *Queries) ListCommentsForRound(ctx context.Context, roundID string) ([]ListCommentsForRoundRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsForRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsForRoundRow
	for rows.Next() {
		var i ListCommentsForRoundRow
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.PlayerID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
