// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disputes.sql

package db

import (
	"context"
	"database/sql"
)

const countDisputesForJump = `-- name: CountDisputesForJump :one
SELECT count(*) FROM disputes WHERE jump_id = $1
`

func (q *Queries) CountDisputesForJump(ctx context.Context, jumpID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDisputesForJump, jumpID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDispute = `-- name: GetDispute :one
SELECT id, jump_id, raised_by_player_id, concern, details, status,
       resolution, resolution_reason, resolved_by_player_id,
       override_resolution, override_reason, override_by_player_id
FROM disputes
WHERE id = $1
`

type GetDisputeRow struct {
	ID                 string
	JumpID             string
	RaisedByPlayerID   string
	Concern            string
	Details            string
	Status             string
	Resolution         sql.NullString
	ResolutionReason   sql.NullString
	ResolvedByPlayerID sql.NullString
	OverrideResolution sql.NullString
	OverrideReason     sql.NullString
	OverrideByPlayerID sql.NullString
}

func (q *Queries) GetDispute(ctx context.Context, id string) (GetDisputeRow, error) {
	row := q.db.QueryRowContext(ctx, getDispute, id)
	var i GetDisputeRow
	err := row.Scan(
		&i.ID,
		&i.JumpID,
		&i.RaisedByPlayerID,
		&i.Concern,
		&i.Details,
		&i.Status,
		&i.Resolution,
		&i.ResolutionReason,
		&i.ResolvedByPlayerID,
		&i.OverrideResolution,
		&i.OverrideReason,
		&i.OverrideByPlayerID,
	)
	return i, err
}

const insertDispute = `-- name: InsertDispute :exec
INSERT INTO disputes (id, jump_id, raised_by_player_id, concern, details, status)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDisputeParams struct {
	ID               string
	JumpID           string
	RaisedByPlayerID string
	Concern          string
	Details          string
	Status           string
}

func (q *Queries) InsertDispute(ctx context.Context, arg InsertDisputeParams) error {
	_, err := q.db.ExecContext(ctx, insertDispute,
		arg.ID,
		arg.JumpID,
		arg.RaisedByPlayerID,
		arg.Concern,
		arg.Details,
		arg.Status,
	)
	return err
}

const listDisputesForJump = `-- name: ListDisputesForJump :many
SELECT id, jump_id, raised_by_player_id, concern, details, status,
       resolution, resolution_reason, resolved_by_player_id,
       override_resolution, override_reason, override_by_player_id
FROM disputes
WHERE jump_id = $1
ORDER BY created_at ASC, id ASC
`

type ListDisputesForJumpRow struct {
	ID                 string
	JumpID             string
	RaisedByPlayerID   string
	Concern            string
	Details            string
	Status             string
	Resolution         sql.NullString
	ResolutionReason   sql.NullString
	ResolvedByPlayerID sql.NullString
	OverrideResolution sql.NullString
	OverrideReason     sql.NullString
	OverrideByPlayerID sql.NullString
}

func (q *Queries) ListDisputesForJump(ctx context.Context, jumpID string) ([]ListDisputesForJumpRow, error) {
	rows, err := q.db.QueryContext(ctx, listDisputesForJump, jumpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDisputesForJumpRow
	for rows.Next() {
		var i ListDisputesForJumpRow
		if err := rows.Scan(
			&i.ID,
			&i.JumpID,
			&i.RaisedByPlayerID,
			&i.Concern,
			&i.Details,
			&i.Status,
			&i.Resolution,
			&i.ResolutionReason,
			&i.ResolvedByPlayerID,
			&i.OverrideResolution,
			&i.OverrideReason,
			&i.OverrideByPlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDisputeOverride = `-- name: UpdateDisputeOverride :exec
UPDATE disputes
SET status = 'Overridden', override_resolution = $2, override_reason = $3, override_by_player_id = $4
WHERE id = $1
`

type UpdateDisputeOverrideParams struct {
	ID                 string
	OverrideResolution sql.NullString
	OverrideReason     sql.NullString
	OverrideByPlayerID sql.NullString
}

func (q *Queries) UpdateDisputeOverride(ctx context.Context, arg UpdateDisputeOverrideParams) error {
	_, err := q.db.ExecContext(ctx, updateDisputeOverride,
		arg.ID,
		arg.OverrideResolution,
		arg.OverrideReason,
		arg.OverrideByPlayerID,
	)
	return err
}

const updateDisputeResolution = `-- name: UpdateDisputeResolution :exec
UPDATE disputes
SET status = 'Resolved', resolution = $2, resolution_reason = $3, resolved_by_player_id = $4
WHERE id = $1
`

type UpdateDisputeResolutionParams struct {
	ID                 string
	Resolution         sql.NullString
	ResolutionReason   sql.NullString
	ResolvedByPlayerID sql.NullString
}

func (q *Queries) UpdateDisputeResolution(ctx context.Context, arg UpdateDisputeResolutionParams) error {
	_, err := q.db.ExecContext(ctx, updateDisputeResolution,
		arg.ID,
		arg.Resolution,
		arg.ResolutionReason,
		arg.ResolvedByPlayerID,
	)
	return err
}
