// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const insertEvidence = `-- name: InsertEvidence :exec
INSERT INTO evidences (id, jump_id, player_id, upload_authorization_id, caption, media_object_key, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEvidenceParams struct {
	ID                    string
	JumpID                string
	PlayerID              string
	UploadAuthorizationID sql.NullString
	Caption               string
	MediaObjectKey        string
	CreatedAt             time.Time
}

func (q *Queries) InsertEvidence(ctx context.Context, arg InsertEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, insertEvidence,
		arg.ID,
		arg.JumpID,
		arg.PlayerID,
		arg.UploadAuthorizationID,
		arg.Caption,
		arg.MediaObjectKey,
		arg.CreatedAt,
	)
	return err
}

const updateEvidenceCaption = `-- name: UpdateEvidenceCaption :exec
UPDATE evidences
SET caption = $2
WHERE jump_id = $1
`

type UpdateEvidenceCaptionParams struct {
	JumpID  string
	Caption string
}

func (q *Queries) UpdateEvidenceCaption(ctx context.Context, arg UpdateEvidenceCaptionParams) error {
	_, err := q.db.ExecContext(ctx, updateEvidenceCaption, arg.JumpID, arg.Caption)
	return err
}
