// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"
)

const createGroup = `-- name: CreateGroup :exec
INSERT INTO groups (id, name)
VALUES ($1, $2)
`

type CreateGroupParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.ExecContext(ctx, createGroup, arg.ID, arg.Name)
	return err
}

const createGroupMembership = `-- name: CreateGroupMembership :exec
INSERT INTO group_memberships (group_id, player_id, role)
VALUES ($1, $2, $3)
`

type CreateGroupMembershipParams struct {
	GroupID  string
	PlayerID string
	Role     string
}

func (q *Queries) CreateGroupMembership(ctx context.Context, arg CreateGroupMembershipParams) error {
	_, err := q.db.ExecContext(ctx, createGroupMembership, arg.GroupID, arg.PlayerID, arg.Role)
	return err
}

const getGroupMembership = `-- name: GetGroupMembership :one
SELECT groups.id, groups.name, group_memberships.player_id, group_memberships.role
FROM group_memberships
JOIN groups ON groups.id = group_memberships.group_id
WHERE group_memberships.group_id = $1 AND group_memberships.player_id = $2
`

type GetGroupMembershipParams struct {
	GroupID  string
	PlayerID string
}

type GetGroupMembershipRow struct {
	ID       string
	Name     string
	PlayerID string
	Role     string
}

func (q *Queries) GetGroupMembership(ctx context.Context, arg GetGroupMembershipParams) (GetGroupMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, getGroupMembership, arg.GroupID, arg.PlayerID)
	var i GetGroupMembershipRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlayerID,
		&i.Role,
	)
	return i, err
}

const listGroupMembershipsByPlayerID = `-- name: ListGroupMembershipsByPlayerID :many
SELECT groups.id, groups.name, group_memberships.player_id, group_memberships.role
FROM group_memberships
JOIN groups ON groups.id = group_memberships.group_id
WHERE group_memberships.player_id = $1
ORDER BY groups.name
`

type ListGroupMembershipsByPlayerIDRow struct {
	ID       string
	Name     string
	PlayerID string
	Role     string
}

func (q *Queries) ListGroupMembershipsByPlayerID(ctx context.Context, playerID string) ([]ListGroupMembershipsByPlayerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembershipsByPlayerID, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembershipsByPlayerIDRow
	for rows.Next() {
		var i ListGroupMembershipsByPlayerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PlayerID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
