// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getGroup = `-- name: GetGroup :one
SELECT id, name FROM groups WHERE id = $1
`

type GetGroupRow struct {
	ID   string
	Name string
}

func (q *Queries) GetGroup(ctx context.Context, id string) (GetGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i GetGroupRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, group_id, token, created_by_player_id, used_by_player_id, expires_at
FROM invites
WHERE token = $1
`

type GetInviteByTokenRow struct {
	ID                string
	GroupID           string
	Token             string
	CreatedByPlayerID string
	UsedByPlayerID    sql.NullString
	ExpiresAt         time.Time
}

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (GetInviteByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getInviteByToken, token)
	var i GetInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Token,
		&i.CreatedByPlayerID,
		&i.UsedByPlayerID,
		&i.ExpiresAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT group_id, player_id, role FROM group_memberships
WHERE player_id = $1 AND group_id = $2
`

type GetMembershipParams struct {
	PlayerID string
	GroupID  string
}

type GetMembershipRow struct {
	GroupID  string
	PlayerID string
	Role     string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, getMembership, arg.PlayerID, arg.GroupID)
	var i GetMembershipRow
	err := row.Scan(&i.GroupID, &i.PlayerID, &i.Role)
	return i, err
}

const getMembershipRole = `-- name: GetMembershipRole :one
SELECT role FROM group_memberships
WHERE player_id = $1 AND group_id = $2
`

type GetMembershipRoleParams struct {
	PlayerID string
	GroupID  string
}

func (q *Queries) GetMembershipRole(ctx context.Context, arg GetMembershipRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getMembershipRole, arg.PlayerID, arg.GroupID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const insertGroup = `-- name: InsertGroup :exec
INSERT INTO groups (id, name)
VALUES ($1, $2)
`

type InsertGroupParams struct {
	ID   string
	Name string
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertGroup, arg.ID, arg.Name)
	return err
}

const insertInvite = `-- name: InsertInvite :exec
INSERT INTO invites (id, group_id, token, created_by_player_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertInviteParams struct {
	ID                string
	GroupID           string
	Token             string
	CreatedByPlayerID string
	ExpiresAt         time.Time
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.ExecContext(ctx, insertInvite,
		arg.ID,
		arg.GroupID,
		arg.Token,
		arg.CreatedByPlayerID,
		arg.ExpiresAt,
	)
	return err
}

const insertMembership = `-- name: InsertMembership :exec
INSERT INTO group_memberships (group_id, player_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, player_id) DO UPDATE SET role = EXCLUDED.role
`

type InsertMembershipParams struct {
	GroupID  string
	PlayerID string
	Role     string
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) error {
	_, err := q.db.ExecContext(ctx, insertMembership, arg.GroupID, arg.PlayerID, arg.Role)
	return err
}

const listMembershipsForPlayer = `-- name: ListMembershipsForPlayer :many
SELECT groups.id, groups.name, group_memberships.group_id, group_memberships.player_id, group_memberships.role
FROM group_memberships
JOIN groups ON groups.id = group_memberships.group_id
WHERE group_memberships.player_id = $1
ORDER BY groups.name
`

type ListMembershipsForPlayerRow struct {
	ID       string
	Name     string
	GroupID  string
	PlayerID string
	Role     string
}

func (q *Queries) ListMembershipsForPlayer(ctx context.Context, playerID string) ([]ListMembershipsForPlayerRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsForPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsForPlayerRow
	for rows.Next() {
		var i ListMembershipsForPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupID,
			&i.PlayerID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteUsed = `-- name: MarkInviteUsed :exec
UPDATE invites
SET used_by_player_id = $1
WHERE token = $2 AND used_by_player_id IS NULL
`

type MarkInviteUsedParams struct {
	UsedByPlayerID sql.NullString
	Token          string
}

func (q *Queries) MarkInviteUsed(ctx context.Context, arg MarkInviteUsedParams) error {
	_, err := q.db.ExecContext(ctx, markInviteUsed, arg.UsedByPlayerID, arg.Token)
	return err
}
