// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"
)

const createCommunity = `-- name: CreateCommunity :exec
INSERT INTO communities (id, display_name)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
`

type CreateCommunityParams struct {
	ID          string
	DisplayName string
}

func (q *Queries) CreateCommunity(ctx context.Context, arg CreateCommunityParams) error {
	_, err := q.db.ExecContext(ctx, createCommunity, arg.ID, arg.DisplayName)
	return err
}

const createPlayer = `-- name: CreatePlayer :exec
INSERT INTO players (id, display_name)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
`

type CreatePlayerParams struct {
	ID          string
	DisplayName string
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) error {
	_, err := q.db.ExecContext(ctx, createPlayer, arg.ID, arg.DisplayName)
	return err
}

const findCommunity = `-- name: FindCommunity :one
SELECT id, display_name, created_at
FROM communities
WHERE id = $1
`

func (q *Queries) FindCommunity(ctx context.Context, id string) (Community, error) {
	row := q.db.QueryRowContext(ctx, findCommunity, id)
	var i Community
	err := row.Scan(&i.ID, &i.DisplayName, &i.CreatedAt)
	return i, err
}

const findPlayer = `-- name: FindPlayer :one
SELECT id, display_name, created_at
FROM players
WHERE id = $1
`

func (q *Queries) FindPlayer(ctx context.Context, id string) (Player, error) {
	row := q.db.QueryRowContext(ctx, findPlayer, id)
	var i Player
	err := row.Scan(&i.ID, &i.DisplayName, &i.CreatedAt)
	return i, err
}

const getExternalIdentity = `-- name: GetExternalIdentity :one
SELECT player_id, community_id
FROM external_identity
WHERE platform = $1 AND platform_server_id = $2 AND platform_user_id = $3
`

type GetExternalIdentityParams struct {
	Platform         string
	PlatformServerID string
	PlatformUserID   string
}

type GetExternalIdentityRow struct {
	PlayerID    string
	CommunityID string
}

func (q *Queries) GetExternalIdentity(ctx context.Context, arg GetExternalIdentityParams) (GetExternalIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getExternalIdentity, arg.Platform, arg.PlatformServerID, arg.PlatformUserID)
	var i GetExternalIdentityRow
	err := row.Scan(&i.PlayerID, &i.CommunityID)
	return i, err
}

const insertExternalIdentity = `-- name: InsertExternalIdentity :exec
INSERT INTO external_identity (platform, platform_server_id, platform_user_id, player_id, community_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (platform, platform_server_id, platform_user_id) DO NOTHING
`

type InsertExternalIdentityParams struct {
	Platform         string
	PlatformServerID string
	PlatformUserID   string
	PlayerID         string
	CommunityID      string
}

func (q *Queries) InsertExternalIdentity(ctx context.Context, arg InsertExternalIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertExternalIdentity,
		arg.Platform,
		arg.PlatformServerID,
		arg.PlatformUserID,
		arg.PlayerID,
		arg.CommunityID,
	)
	return err
}

const updatePlayerDisplayName = `-- name: UpdatePlayerDisplayName :exec
UPDATE players
SET display_name = $2
WHERE id = $1
`

type UpdatePlayerDisplayNameParams struct {
	ID          string
	DisplayName string
}

func (q *Queries) UpdatePlayerDisplayName(ctx context.Context, arg UpdatePlayerDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerDisplayName, arg.ID, arg.DisplayName)
	return err
}
