// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: judgments.sql

package db

import (
	"context"
	"database/sql"
)

const createJudgment = `-- name: CreateJudgment :exec
INSERT INTO judgments (id, jump_id, player_id, difficulty, transgression, creativity, presentation, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (jump_id, player_id) 
DO UPDATE SET 
    difficulty = EXCLUDED.difficulty,
    transgression = EXCLUDED.transgression,
    creativity = EXCLUDED.creativity,
    presentation = EXCLUDED.presentation
`

type CreateJudgmentParams struct {
	ID            string
	JumpID        string
	PlayerID      string
	Difficulty    int32
	Transgression int32
	Creativity    int32
	Presentation  int32
}

func (q *Queries) CreateJudgment(ctx context.Context, arg CreateJudgmentParams) error {
	_, err := q.db.ExecContext(ctx, createJudgment,
		arg.ID,
		arg.JumpID,
		arg.PlayerID,
		arg.Difficulty,
		arg.Transgression,
		arg.Creativity,
		arg.Presentation,
	)
	return err
}

const getJudgment = `-- name: GetJudgment :one
SELECT id, jump_id, player_id, difficulty, transgression, creativity, presentation, created_at FROM judgments
WHERE jump_id = $1 AND player_id = $2
`

type GetJudgmentParams struct {
	JumpID   string
	PlayerID string
}

func (q *Queries) GetJudgment(ctx context.Context, arg GetJudgmentParams) (Judgment, error) {
	row := q.db.QueryRowContext(ctx, getJudgment, arg.JumpID, arg.PlayerID)
	var i Judgment
	err := row.Scan(
		&i.ID,
		&i.JumpID,
		&i.PlayerID,
		&i.Difficulty,
		&i.Transgression,
		&i.Creativity,
		&i.Presentation,
		&i.CreatedAt,
	)
	return i, err
}

const listJumpsForJudging = `-- name: ListJumpsForJudging :many
SELECT j.id, j.player_id, j.source, j.destination, j.food
FROM jumps j
WHERE j.group_id = $1 
  AND j.status = 'Performed Jump'
  AND j.player_id != $2
  AND NOT EXISTS (
      SELECT 1 FROM judgments sub
      WHERE sub.jump_id = j.id AND sub.player_id = $2
  )
ORDER BY j.created_at DESC
`

type ListJumpsForJudgingParams struct {
	GroupID  sql.NullString
	PlayerID string
}

type ListJumpsForJudgingRow struct {
	ID          string
	PlayerID    string
	Source      string
	Destination string
	Food        string
}

func (q *Queries) ListJumpsForJudging(ctx context.Context, arg ListJumpsForJudgingParams) ([]ListJumpsForJudgingRow, error) {
	rows, err := q.db.QueryContext(ctx, listJumpsForJudging, arg.GroupID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJumpsForJudgingRow
	for rows.Next() {
		var i ListJumpsForJudgingRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Source,
			&i.Destination,
			&i.Food,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
