// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: judgments.sql

package db

import (
	"context"
	"database/sql"
)

const createGuestSession = `-- name: CreateGuestSession :one
INSERT INTO guest_sessions (id)
VALUES ($1)
RETURNING id, judgment_count, created_at
`

func (q *Queries) CreateGuestSession(ctx context.Context, id string) (GuestSession, error) {
	row := q.db.QueryRowContext(ctx, createGuestSession, id)
	var i GuestSession
	err := row.Scan(&i.ID, &i.JudgmentCount, &i.CreatedAt)
	return i, err
}

const getGuestJudgment = `-- name: GetGuestJudgment :one
SELECT id, jump_id, player_id, guest_session_id, provenance, open_month_id, commitment, transgression, creativity, presentation
FROM judgments
WHERE jump_id = $1 AND guest_session_id = $2
`

type GetGuestJudgmentParams struct {
	JumpID         string
	GuestSessionID sql.NullString
}

type GetGuestJudgmentRow struct {
	ID             string
	JumpID         string
	PlayerID       sql.NullString
	GuestSessionID sql.NullString
	Provenance     string
	OpenMonthID    sql.NullString
	Commitment     int32
	Transgression  int32
	Creativity     int32
	Presentation   int32
}

func (q *Queries) GetGuestJudgment(ctx context.Context, arg GetGuestJudgmentParams) (GetGuestJudgmentRow, error) {
	row := q.db.QueryRowContext(ctx, getGuestJudgment, arg.JumpID, arg.GuestSessionID)
	var i GetGuestJudgmentRow
	err := row.Scan(
		&i.ID,
		&i.JumpID,
		&i.PlayerID,
		&i.GuestSessionID,
		&i.Provenance,
		&i.OpenMonthID,
		&i.Commitment,
		&i.Transgression,
		&i.Creativity,
		&i.Presentation,
	)
	return i, err
}

const getGuestSession = `-- name: GetGuestSession :one
SELECT id, judgment_count, created_at
FROM guest_sessions
WHERE id = $1
`

func (q *Queries) GetGuestSession(ctx context.Context, id string) (GuestSession, error) {
	row := q.db.QueryRowContext(ctx, getGuestSession, id)
	var i GuestSession
	err := row.Scan(&i.ID, &i.JudgmentCount, &i.CreatedAt)
	return i, err
}

const getGuestSessionJudgmentCount = `-- name: GetGuestSessionJudgmentCount :one
SELECT judgment_count
FROM guest_sessions
WHERE id = $1
`

func (q *Queries) GetGuestSessionJudgmentCount(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getGuestSessionJudgmentCount, id)
	var judgment_count int32
	err := row.Scan(&judgment_count)
	return judgment_count, err
}

const getPlayerJudgment = `-- name: GetPlayerJudgment :one
SELECT id, jump_id, player_id, guest_session_id, provenance, open_month_id, commitment, transgression, creativity, presentation
FROM judgments
WHERE jump_id = $1 AND player_id = $2
`

type GetPlayerJudgmentParams struct {
	JumpID   string
	PlayerID sql.NullString
}

type GetPlayerJudgmentRow struct {
	ID             string
	JumpID         string
	PlayerID       sql.NullString
	GuestSessionID sql.NullString
	Provenance     string
	OpenMonthID    sql.NullString
	Commitment     int32
	Transgression  int32
	Creativity     int32
	Presentation   int32
}

func (q *Queries) GetPlayerJudgment(ctx context.Context, arg GetPlayerJudgmentParams) (GetPlayerJudgmentRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerJudgment, arg.JumpID, arg.PlayerID)
	var i GetPlayerJudgmentRow
	err := row.Scan(
		&i.ID,
		&i.JumpID,
		&i.PlayerID,
		&i.GuestSessionID,
		&i.Provenance,
		&i.OpenMonthID,
		&i.Commitment,
		&i.Transgression,
		&i.Creativity,
		&i.Presentation,
	)
	return i, err
}

const incrementGuestSessionJudgmentCount = `-- name: IncrementGuestSessionJudgmentCount :exec
UPDATE guest_sessions
SET judgment_count = judgment_count + 1
WHERE id = $1
`

func (q *Queries) IncrementGuestSessionJudgmentCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementGuestSessionJudgmentCount, id)
	return err
}

const insertGuestJudgment = `-- name: InsertGuestJudgment :exec
INSERT INTO judgments (id, jump_id, player_id, guest_session_id, provenance, open_month_id, commitment, transgression, creativity, presentation)
VALUES ($1, $2, NULL, $3, $4, $5, $6, $7, $8, $9)
`

type InsertGuestJudgmentParams struct {
	ID             string
	JumpID         string
	GuestSessionID sql.NullString
	Provenance     string
	OpenMonthID    sql.NullString
	Commitment     int32
	Transgression  int32
	Creativity     int32
	Presentation   int32
}

func (q *Queries) InsertGuestJudgment(ctx context.Context, arg InsertGuestJudgmentParams) error {
	_, err := q.db.ExecContext(ctx, insertGuestJudgment,
		arg.ID,
		arg.JumpID,
		arg.GuestSessionID,
		arg.Provenance,
		arg.OpenMonthID,
		arg.Commitment,
		arg.Transgression,
		arg.Creativity,
		arg.Presentation,
	)
	return err
}

const insertPlayerJudgment = `-- name: InsertPlayerJudgment :exec
INSERT INTO judgments (id, jump_id, player_id, guest_session_id, provenance, open_month_id, commitment, transgression, creativity, presentation)
VALUES ($1, $2, $3, NULL, $4, $5, $6, $7, $8, $9)
`

type InsertPlayerJudgmentParams struct {
	ID            string
	JumpID        string
	PlayerID      sql.NullString
	Provenance    string
	OpenMonthID   sql.NullString
	Commitment    int32
	Transgression int32
	Creativity    int32
	Presentation  int32
}

func (q *Queries) InsertPlayerJudgment(ctx context.Context, arg InsertPlayerJudgmentParams) error {
	_, err := q.db.ExecContext(ctx, insertPlayerJudgment,
		arg.ID,
		arg.JumpID,
		arg.PlayerID,
		arg.Provenance,
		arg.OpenMonthID,
		arg.Commitment,
		arg.Transgression,
		arg.Creativity,
		arg.Presentation,
	)
	return err
}

const listJudgmentsForJump = `-- name: ListJudgmentsForJump :many
SELECT id, jump_id, player_id, guest_session_id, provenance, open_month_id, commitment, transgression, creativity, presentation
FROM judgments
WHERE jump_id = $1
`

type ListJudgmentsForJumpRow struct {
	ID             string
	JumpID         string
	PlayerID       sql.NullString
	GuestSessionID sql.NullString
	Provenance     string
	OpenMonthID    sql.NullString
	Commitment     int32
	Transgression  int32
	Creativity     int32
	Presentation   int32
}

func (q *Queries) ListJudgmentsForJump(ctx context.Context, jumpID string) ([]ListJudgmentsForJumpRow, error) {
	rows, err := q.db.QueryContext(ctx, listJudgmentsForJump, jumpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJudgmentsForJumpRow
	for rows.Next() {
		var i ListJudgmentsForJumpRow
		if err := rows.Scan(
			&i.ID,
			&i.JumpID,
			&i.PlayerID,
			&i.GuestSessionID,
			&i.Provenance,
			&i.OpenMonthID,
			&i.Commitment,
			&i.Transgression,
			&i.Creativity,
			&i.Presentation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
