// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: judgments.sql

package db

import (
	"context"
	"database/sql"
)

const createGuestSession = `-- name: CreateGuestSession :one
INSERT INTO guest_sessions (id)
VALUES ($1)
RETURNING id, judgment_count, created_at
`

func (q *Queries) CreateGuestSession(ctx context.Context, id string) (GuestSession, error) {
	row := q.db.QueryRowContext(ctx, createGuestSession, id)
	var i GuestSession
	err := row.Scan(&i.ID, &i.JudgmentCount, &i.CreatedAt)
	return i, err
}

const getGuestSession = `-- name: GetGuestSession :one
SELECT id, judgment_count, created_at
FROM guest_sessions
WHERE id = $1
`

func (q *Queries) GetGuestSession(ctx context.Context, id string) (GuestSession, error) {
	row := q.db.QueryRowContext(ctx, getGuestSession, id)
	var i GuestSession
	err := row.Scan(&i.ID, &i.JudgmentCount, &i.CreatedAt)
	return i, err
}

const getGuestSessionJudgmentCount = `-- name: GetGuestSessionJudgmentCount :one
SELECT judgment_count
FROM guest_sessions
WHERE id = $1
`

func (q *Queries) GetGuestSessionJudgmentCount(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getGuestSessionJudgmentCount, id)
	var judgment_count int32
	err := row.Scan(&judgment_count)
	return judgment_count, err
}

const getPlayerJudgment = `-- name: GetPlayerJudgment :one
SELECT id, jump_id, player_id, guest_session_id, provenance, commitment, transgression, creativity, presentation
FROM judgments
WHERE jump_id = $1 AND player_id = $2
`

type GetPlayerJudgmentParams struct {
	JumpID   string
	PlayerID sql.NullString
}

type GetPlayerJudgmentRow struct {
	ID             string
	JumpID         string
	PlayerID       sql.NullString
	GuestSessionID sql.NullString
	Provenance     string
	Commitment     int32
	Transgression  int32
	Creativity     int32
	Presentation   int32
}

func (q *Queries) GetPlayerJudgment(ctx context.Context, arg GetPlayerJudgmentParams) (GetPlayerJudgmentRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerJudgment, arg.JumpID, arg.PlayerID)
	var i GetPlayerJudgmentRow
	err := row.Scan(
		&i.ID,
		&i.JumpID,
		&i.PlayerID,
		&i.GuestSessionID,
		&i.Provenance,
		&i.Commitment,
		&i.Transgression,
		&i.Creativity,
		&i.Presentation,
	)
	return i, err
}

const incrementGuestSessionJudgmentCount = `-- name: IncrementGuestSessionJudgmentCount :exec
UPDATE guest_sessions
SET judgment_count = judgment_count + 1
WHERE id = $1
`

func (q *Queries) IncrementGuestSessionJudgmentCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementGuestSessionJudgmentCount, id)
	return err
}

const listJudgmentsForJump = `-- name: ListJudgmentsForJump :many
SELECT id, jump_id, player_id, guest_session_id, provenance, commitment, transgression, creativity, presentation
FROM judgments
WHERE jump_id = $1
`

type ListJudgmentsForJumpRow struct {
	ID             string
	JumpID         string
	PlayerID       sql.NullString
	GuestSessionID sql.NullString
	Provenance     string
	Commitment     int32
	Transgression  int32
	Creativity     int32
	Presentation   int32
}

func (q *Queries) ListJudgmentsForJump(ctx context.Context, jumpID string) ([]ListJudgmentsForJumpRow, error) {
	rows, err := q.db.QueryContext(ctx, listJudgmentsForJump, jumpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJudgmentsForJumpRow
	for rows.Next() {
		var i ListJudgmentsForJumpRow
		if err := rows.Scan(
			&i.ID,
			&i.JumpID,
			&i.PlayerID,
			&i.GuestSessionID,
			&i.Provenance,
			&i.Commitment,
			&i.Transgression,
			&i.Creativity,
			&i.Presentation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJumpsForJudging = `-- name: ListJumpsForJudging :many
SELECT j.id, j.player_id, j.source, j.destination, j.food
FROM jumps j
WHERE j.group_id = $1
  AND j.status = 'Performed Jump'
  AND j.player_id != $2
  AND NOT EXISTS (
      SELECT 1 FROM judgments sub
      WHERE sub.jump_id = j.id AND sub.player_id = $2
  )
ORDER BY j.created_at DESC
`

type ListJumpsForJudgingParams struct {
	GroupID  sql.NullString
	PlayerID string
}

type ListJumpsForJudgingRow struct {
	ID          string
	PlayerID    string
	Source      string
	Destination string
	Food        string
}

func (q *Queries) ListJumpsForJudging(ctx context.Context, arg ListJumpsForJudgingParams) ([]ListJumpsForJudgingRow, error) {
	rows, err := q.db.QueryContext(ctx, listJumpsForJudging, arg.GroupID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJumpsForJudgingRow
	for rows.Next() {
		var i ListJumpsForJudgingRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Source,
			&i.Destination,
			&i.Food,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGuestJudgment = `-- name: UpsertGuestJudgment :one
WITH upsert AS (
  INSERT INTO judgments (id, jump_id, player_id, guest_session_id, provenance, commitment, transgression, creativity, presentation)
  VALUES ($1, $2, NULL, $3, $4, $5, $6, $7, $8)
  ON CONFLICT (jump_id, guest_session_id) WHERE guest_session_id IS NOT NULL DO UPDATE SET
    commitment = EXCLUDED.commitment,
    transgression = EXCLUDED.transgression,
    creativity = EXCLUDED.creativity,
    presentation = EXCLUDED.presentation
  RETURNING (xmax = 0) AS created
)
SELECT created FROM upsert
`

type UpsertGuestJudgmentParams struct {
	ID             string
	JumpID         string
	GuestSessionID sql.NullString
	Provenance     string
	Commitment     int32
	Transgression  int32
	Creativity     int32
	Presentation   int32
}

func (q *Queries) UpsertGuestJudgment(ctx context.Context, arg UpsertGuestJudgmentParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, upsertGuestJudgment,
		arg.ID,
		arg.JumpID,
		arg.GuestSessionID,
		arg.Provenance,
		arg.Commitment,
		arg.Transgression,
		arg.Creativity,
		arg.Presentation,
	)
	var created bool
	err := row.Scan(&created)
	return created, err
}

const upsertPlayerJudgment = `-- name: UpsertPlayerJudgment :one
WITH upsert AS (
  INSERT INTO judgments (id, jump_id, player_id, guest_session_id, provenance, commitment, transgression, creativity, presentation)
  VALUES ($1, $2, $3, NULL, $4, $5, $6, $7, $8)
  ON CONFLICT (jump_id, player_id) WHERE player_id IS NOT NULL DO UPDATE SET
    commitment = EXCLUDED.commitment,
    transgression = EXCLUDED.transgression,
    creativity = EXCLUDED.creativity,
    presentation = EXCLUDED.presentation
  RETURNING (xmax = 0) AS created
)
SELECT created FROM upsert
`

type UpsertPlayerJudgmentParams struct {
	ID            string
	JumpID        string
	PlayerID      sql.NullString
	Provenance    string
	Commitment    int32
	Transgression int32
	Creativity    int32
	Presentation  int32
}

func (q *Queries) UpsertPlayerJudgment(ctx context.Context, arg UpsertPlayerJudgmentParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, upsertPlayerJudgment,
		arg.ID,
		arg.JumpID,
		arg.PlayerID,
		arg.Provenance,
		arg.Commitment,
		arg.Transgression,
		arg.Creativity,
		arg.Presentation,
	)
	var created bool
	err := row.Scan(&created)
	return created, err
}
