// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jumps.sql

package db

import (
	"context"
	"database/sql"
)

const advanceJumpToJudged = `-- name: AdvanceJumpToJudged :exec
UPDATE jumps
SET status = 'Judged Jump'
WHERE id = $1 AND status = 'Performed Jump'
`

func (q *Queries) AdvanceJumpToJudged(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, advanceJumpToJudged, id)
	return err
}

const getJump = `-- name: GetJump :one
SELECT id, player_id, season_id, status, source, destination, food, final_score, grace_period_expires_at
FROM jumps
WHERE id = $1
`

type GetJumpRow struct {
	ID                   string
	PlayerID             string
	SeasonID             sql.NullString
	Status               string
	Source               string
	Destination          string
	Food                 string
	FinalScore           sql.NullInt32
	GracePeriodExpiresAt sql.NullTime
}

func (q *Queries) GetJump(ctx context.Context, id string) (GetJumpRow, error) {
	row := q.db.QueryRowContext(ctx, getJump, id)
	var i GetJumpRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.SeasonID,
		&i.Status,
		&i.Source,
		&i.Destination,
		&i.Food,
		&i.FinalScore,
		&i.GracePeriodExpiresAt,
	)
	return i, err
}
