// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lore.sql

package db

import (
	"context"
)

const listRevealedReactionsForCommunity = `-- name: ListRevealedReactionsForCommunity :many
SELECT
    rxn.jump_id,
    s.stance AS stamp_stance,
    j.round_id,
    j.caption AS jump_caption,
    j.player_id AS jump_player_id
FROM reactions rxn
JOIN jumps j ON j.id = rxn.jump_id
JOIN rounds r ON r.id = j.round_id AND r.status = 'revealed'
JOIN stamps s ON s.id = rxn.stamp_id
WHERE r.community_id = $1
ORDER BY j.id, rxn.created_at
`

type ListRevealedReactionsForCommunityRow struct {
	JumpID       string
	StampStance  string
	RoundID      string
	JumpCaption  string
	JumpPlayerID string
}

func (q *Queries) ListRevealedReactionsForCommunity(ctx context.Context, communityID string) ([]ListRevealedReactionsForCommunityRow, error) {
	rows, err := q.db.QueryContext(ctx, listRevealedReactionsForCommunity, communityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevealedReactionsForCommunityRow
	for rows.Next() {
		var i ListRevealedReactionsForCommunityRow
		if err := rows.Scan(
			&i.JumpID,
			&i.StampStance,
			&i.RoundID,
			&i.JumpCaption,
			&i.JumpPlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
