// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        string
	RoundID   string
	JumpID    sql.NullString
	PlayerID  string
	Body      string
	CreatedAt time.Time
}

type Commit struct {
	ID          string
	RoundID     string
	PlayerID    string
	CommittedAt time.Time
}

type Community struct {
	ID          string
	DisplayName string
	CreatedAt   time.Time
}

type ExternalIdentity struct {
	Platform         string
	PlatformServerID string
	PlatformUserID   string
	PlayerID         string
	CommunityID      string
	CreatedAt        time.Time
}

type Jump struct {
	ID          string
	RoundID     string
	PlayerID    string
	Caption     string
	SubmittedAt time.Time
}

type JumpEvidence struct {
	ID        string
	JumpID    string
	Url       string
	SortOrder int32
}

type Player struct {
	ID          string
	DisplayName string
	CreatedAt   time.Time
}

type Prompt struct {
	ID        string
	PackID    string
	Copy      string
	Theme     string
	CostTier  string
	CreatedAt time.Time
}

type PromptPack struct {
	ID          string
	DisplayName string
	Description string
	CreatedAt   time.Time
}

type Reaction struct {
	ID        string
	StampID   string
	JumpID    string
	PlayerID  string
	CreatedAt time.Time
}

type RevealTimeframe struct {
	ID            string
	Label         string
	DurationHours int32
	SortOrder     int32
	CreatedAt     time.Time
}

type Round struct {
	ID          string
	CommunityID string
	PromptID    string
	Status      string
	RevealBy    time.Time
	CreatedBy   string
	CreatedAt   time.Time
}

type Stamp struct {
	ID        string
	Stance    string
	Label     string
	Glyph     string
	Copy      string
	CreatedAt time.Time
}
