// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        string
	Email     string
	CreatedAt time.Time
}

type AuthIdentity struct {
	Provider  string
	Subject   string
	AccountID string
	CreatedAt time.Time
}

type Dispute struct {
	ID                 string
	JumpID             string
	RaisedByPlayerID   string
	Concern            string
	Details            string
	Status             string
	Resolution         sql.NullString
	ResolutionReason   sql.NullString
	ResolvedByPlayerID sql.NullString
	OverrideResolution sql.NullString
	OverrideReason     sql.NullString
	OverrideByPlayerID sql.NullString
	CreatedAt          time.Time
}

type Evidence struct {
	ID                    string
	JumpID                string
	PlayerID              string
	UploadAuthorizationID sql.NullString
	Caption               string
	MediaObjectKey        string
	CreatedAt             time.Time
}

type EvidenceUploadAuthorization struct {
	ID             string
	JumpID         string
	PlayerID       string
	ContentType    string
	MediaObjectKey string
	ExpiresAt      time.Time
	CreatedAt      time.Time
}

type Group struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type GroupMembership struct {
	GroupID   string
	PlayerID  string
	Role      string
	CreatedAt time.Time
}

type GuestSession struct {
	ID            string
	JudgmentCount int32
	CreatedAt     time.Time
}

type Invite struct {
	ID                string
	GroupID           string
	Token             string
	CreatedByPlayerID string
	UsedByPlayerID    sql.NullString
	ExpiresAt         time.Time
	CreatedAt         time.Time
}

type Judgment struct {
	ID             string
	JumpID         string
	PlayerID       sql.NullString
	GuestSessionID sql.NullString
	Provenance     string
	Commitment     int32
	Transgression  int32
	Creativity     int32
	Presentation   int32
	CreatedAt      time.Time
}

type Jump struct {
	ID                   string
	GroupID              sql.NullString
	PlayerID             string
	SeasonID             sql.NullString
	Status               string
	Source               string
	Destination          string
	Food                 string
	FinalScore           sql.NullInt32
	GracePeriodExpiresAt sql.NullTime
	CreatedAt            time.Time
}

type Player struct {
	ID          string
	AccountID   string
	DisplayName string
	CreatedAt   time.Time
}

type Season struct {
	ID                   string
	GroupID              string
	CommissionerPlayerID string
	Status               string
	SubmissionDeadline   time.Time
	JudgingDeadline      time.Time
	CreatedAt            time.Time
}

type SeasonHistory struct {
	ID            string
	SeasonID      string
	Action        string
	ActorPlayerID string
	ActorRole     string
	Override      bool
	FromStatus    string
	ToStatus      string
	CreatedAt     time.Time
}
