// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Account struct {
	ID        string
	Email     string
	CreatedAt time.Time
}

type AuthIdentity struct {
	Provider  string
	Subject   string
	AccountID string
	CreatedAt time.Time
}

type Player struct {
	ID          string
	AccountID   string
	DisplayName string
	CreatedAt   time.Time
}
