// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: open.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const listJumpsForOpenMonth = `-- name: ListJumpsForOpenMonth :many
SELECT id, group_id, player_id, season_id, status, source, destination, food, final_score, grace_period_expires_at
FROM jumps
WHERE created_at >= $1 AND created_at < $2
  AND status IN ('Performed Jump', 'Judged Jump', 'Unjudged Jump', 'Disqualified Jump')
`

type ListJumpsForOpenMonthParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

type ListJumpsForOpenMonthRow struct {
	ID                   string
	GroupID              sql.NullString
	PlayerID             string
	SeasonID             sql.NullString
	Status               string
	Source               string
	Destination          string
	Food                 string
	FinalScore           sql.NullInt32
	GracePeriodExpiresAt sql.NullTime
}

func (q *Queries) ListJumpsForOpenMonth(ctx context.Context, arg ListJumpsForOpenMonthParams) ([]ListJumpsForOpenMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, listJumpsForOpenMonth, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJumpsForOpenMonthRow
	for rows.Next() {
		var i ListJumpsForOpenMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.PlayerID,
			&i.SeasonID,
			&i.Status,
			&i.Source,
			&i.Destination,
			&i.Food,
			&i.FinalScore,
			&i.GracePeriodExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayersForOpenMonth = `-- name: ListPlayersForOpenMonth :many
SELECT DISTINCT p.id, p.display_name
FROM players p
JOIN jumps j ON j.player_id = p.id
WHERE j.created_at >= $1 AND j.created_at < $2
  AND j.status IN ('Performed Jump', 'Judged Jump', 'Unjudged Jump', 'Disqualified Jump')
`

type ListPlayersForOpenMonthParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

type ListPlayersForOpenMonthRow struct {
	ID          string
	DisplayName string
}

func (q *Queries) ListPlayersForOpenMonth(ctx context.Context, arg ListPlayersForOpenMonthParams) ([]ListPlayersForOpenMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayersForOpenMonth, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersForOpenMonthRow
	for rows.Next() {
		var i ListPlayersForOpenMonthRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJumpOpenFinalScore = `-- name: UpdateJumpOpenFinalScore :exec
UPDATE jumps
SET open_final_score = $2
WHERE id = $1
`

type UpdateJumpOpenFinalScoreParams struct {
	ID             string
	OpenFinalScore sql.NullInt32
}

func (q *Queries) UpdateJumpOpenFinalScore(ctx context.Context, arg UpdateJumpOpenFinalScoreParams) error {
	_, err := q.db.ExecContext(ctx, updateJumpOpenFinalScore, arg.ID, arg.OpenFinalScore)
	return err
}

const upsertOpenStanding = `-- name: UpsertOpenStanding :one
INSERT INTO open_standings (id, year, month, player_id, score, judged_jumps)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (year, month, player_id) DO UPDATE SET
    score = EXCLUDED.score,
    judged_jumps = EXCLUDED.judged_jumps,
    updated_at = now()
RETURNING id
`

type UpsertOpenStandingParams struct {
	ID          string
	Year        int32
	Month       int32
	PlayerID    string
	Score       int32
	JudgedJumps int32
}

func (q *Queries) UpsertOpenStanding(ctx context.Context, arg UpsertOpenStandingParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertOpenStanding,
		arg.ID,
		arg.Year,
		arg.Month,
		arg.PlayerID,
		arg.Score,
		arg.JudgedJumps,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
