// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"
)

const getGroupPlayers = `-- name: GetGroupPlayers :many
SELECT players.id, players.display_name
FROM group_memberships
JOIN players ON players.id = group_memberships.player_id
WHERE group_memberships.group_id = $1
`

type GetGroupPlayersRow struct {
	ID          string
	DisplayName string
}

func (q *Queries) GetGroupPlayers(ctx context.Context, groupID string) ([]GetGroupPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupPlayers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupPlayersRow
	for rows.Next() {
		var i GetGroupPlayersRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
