// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prompts.sql

package db

import (
	"context"
)

const getPrompt = `-- name: GetPrompt :one
SELECT id, pack_id, copy, theme, cost_tier, created_at
FROM prompts
WHERE id = $1
`

func (q *Queries) GetPrompt(ctx context.Context, id string) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, getPrompt, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.PackID,
		&i.Copy,
		&i.Theme,
		&i.CostTier,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptPack = `-- name: GetPromptPack :one
SELECT id, display_name, description, created_at
FROM prompt_packs
WHERE id = $1
`

func (q *Queries) GetPromptPack(ctx context.Context, id string) (PromptPack, error) {
	row := q.db.QueryRowContext(ctx, getPromptPack, id)
	var i PromptPack
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listPromptPacks = `-- name: ListPromptPacks :many
SELECT id, display_name, description, created_at
FROM prompt_packs
ORDER BY display_name
`

func (q *Queries) ListPromptPacks(ctx context.Context) ([]PromptPack, error) {
	rows, err := q.db.QueryContext(ctx, listPromptPacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptPack
	for rows.Next() {
		var i PromptPack
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrompts = `-- name: ListPrompts :many
SELECT id, pack_id, copy, theme, cost_tier, created_at
FROM prompts
ORDER BY pack_id, id
`

func (q *Queries) ListPrompts(ctx context.Context) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listPrompts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prompt
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.PackID,
			&i.Copy,
			&i.Theme,
			&i.CostTier,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptsByPack = `-- name: ListPromptsByPack :many
SELECT id, pack_id, copy, theme, cost_tier, created_at
FROM prompts
WHERE pack_id = $1
ORDER BY id
`

func (q *Queries) ListPromptsByPack(ctx context.Context, packID string) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listPromptsByPack, packID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prompt
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.PackID,
			&i.Copy,
			&i.Theme,
			&i.CostTier,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
