// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reactions.sql

package db

import (
	"context"
	"time"
)

const createReaction = `-- name: CreateReaction :exec
INSERT INTO reactions (id, stamp_id, jump_id, player_id, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateReactionParams struct {
	ID        string
	StampID   string
	JumpID    string
	PlayerID  string
	CreatedAt time.Time
}

func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) error {
	_, err := q.db.ExecContext(ctx, createReaction,
		arg.ID,
		arg.StampID,
		arg.JumpID,
		arg.PlayerID,
		arg.CreatedAt,
	)
	return err
}
