// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recap.sql

package db

import (
	"context"
	"time"
)

const listAllCommentsForRound = `-- name: ListAllCommentsForRound :many
SELECT id, round_id, jump_id, player_id, body, created_at
FROM comments
WHERE round_id = $1
ORDER BY created_at
`

func (q *Queries) ListAllCommentsForRound(ctx context.Context, roundID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listAllCommentsForRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.JumpID,
			&i.PlayerID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGhostJumpers = `-- name: ListGhostJumpers :many
SELECT c.player_id, c.committed_at
FROM commits c
LEFT JOIN jumps j ON j.round_id = c.round_id AND j.player_id = c.player_id
WHERE c.round_id = $1 AND j.id IS NULL
ORDER BY c.committed_at
`

type ListGhostJumpersRow struct {
	PlayerID    string
	CommittedAt time.Time
}

func (q *Queries) ListGhostJumpers(ctx context.Context, roundID string) ([]ListGhostJumpersRow, error) {
	rows, err := q.db.QueryContext(ctx, listGhostJumpers, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGhostJumpersRow
	for rows.Next() {
		var i ListGhostJumpersRow
		if err := rows.Scan(&i.PlayerID, &i.CommittedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsForRound = `-- name: ListReactionsForRound :many
SELECT rxn.jump_id, s.stance AS stamp_stance
FROM reactions rxn
JOIN jumps j ON j.id = rxn.jump_id
JOIN stamps s ON s.id = rxn.stamp_id
WHERE j.round_id = $1
ORDER BY rxn.jump_id, rxn.created_at
`

type ListReactionsForRoundRow struct {
	JumpID      string
	StampStance string
}

func (q *Queries) ListReactionsForRound(ctx context.Context, roundID string) ([]ListReactionsForRoundRow, error) {
	rows, err := q.db.QueryContext(ctx, listReactionsForRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReactionsForRoundRow
	for rows.Next() {
		var i ListReactionsForRoundRow
		if err := rows.Scan(&i.JumpID, &i.StampStance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
