// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rounds.sql

package db

import (
	"context"
	"time"
)

const createRound = `-- name: CreateRound :exec
INSERT INTO rounds (id, community_id, prompt_id, status, reveal_by, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateRoundParams struct {
	ID          string
	CommunityID string
	PromptID    string
	Status      string
	RevealBy    time.Time
	CreatedBy   string
	CreatedAt   time.Time
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) error {
	_, err := q.db.ExecContext(ctx, createRound,
		arg.ID,
		arg.CommunityID,
		arg.PromptID,
		arg.Status,
		arg.RevealBy,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const findActiveRound = `-- name: FindActiveRound :one
SELECT id, community_id, prompt_id, status, reveal_by, created_by, created_at
FROM rounds
WHERE community_id = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) FindActiveRound(ctx context.Context, communityID string) (Round, error) {
	row := q.db.QueryRowContext(ctx, findActiveRound, communityID)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.PromptID,
		&i.Status,
		&i.RevealBy,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRound = `-- name: GetRound :one
SELECT id, community_id, prompt_id, status, reveal_by, created_by, created_at
FROM rounds
WHERE id = $1
`

func (q *Queries) GetRound(ctx context.Context, id string) (Round, error) {
	row := q.db.QueryRowContext(ctx, getRound, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.PromptID,
		&i.Status,
		&i.RevealBy,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
