// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seasons.sql

package db

import (
	"context"
	"time"
)

const countSeasons = `-- name: CountSeasons :one
SELECT count(*) FROM seasons
`

func (q *Queries) CountSeasons(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSeasons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveSeasonForGroup = `-- name: GetActiveSeasonForGroup :one
SELECT id, group_id, commissioner_player_id, status
FROM seasons
WHERE group_id = $1 AND status = 'Active'
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveSeasonForGroupRow struct {
	ID                   string
	GroupID              string
	CommissionerPlayerID string
	Status               string
}

func (q *Queries) GetActiveSeasonForGroup(ctx context.Context, groupID string) (GetActiveSeasonForGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveSeasonForGroup, groupID)
	var i GetActiveSeasonForGroupRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommissionerPlayerID,
		&i.Status,
	)
	return i, err
}

const getLatestSeasonForGroup = `-- name: GetLatestSeasonForGroup :one
SELECT id, group_id, commissioner_player_id, status, submission_deadline, judging_deadline
FROM seasons
WHERE group_id = $1
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestSeasonForGroupRow struct {
	ID                   string
	GroupID              string
	CommissionerPlayerID string
	Status               string
	SubmissionDeadline   time.Time
	JudgingDeadline      time.Time
}

func (q *Queries) GetLatestSeasonForGroup(ctx context.Context, groupID string) (GetLatestSeasonForGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestSeasonForGroup, groupID)
	var i GetLatestSeasonForGroupRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommissionerPlayerID,
		&i.Status,
		&i.SubmissionDeadline,
		&i.JudgingDeadline,
	)
	return i, err
}

const getOpenSeasonForGroup = `-- name: GetOpenSeasonForGroup :one
SELECT id, group_id, commissioner_player_id, status, submission_deadline, judging_deadline
FROM seasons
WHERE group_id = $1 AND status IN ('Active', 'Judging Grace Period')
LIMIT 1
`

type GetOpenSeasonForGroupRow struct {
	ID                   string
	GroupID              string
	CommissionerPlayerID string
	Status               string
	SubmissionDeadline   time.Time
	JudgingDeadline      time.Time
}

func (q *Queries) GetOpenSeasonForGroup(ctx context.Context, groupID string) (GetOpenSeasonForGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getOpenSeasonForGroup, groupID)
	var i GetOpenSeasonForGroupRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommissionerPlayerID,
		&i.Status,
		&i.SubmissionDeadline,
		&i.JudgingDeadline,
	)
	return i, err
}

const getSeason = `-- name: GetSeason :one
SELECT id, group_id, commissioner_player_id, status, submission_deadline, judging_deadline
FROM seasons WHERE id = $1
`

type GetSeasonRow struct {
	ID                   string
	GroupID              string
	CommissionerPlayerID string
	Status               string
	SubmissionDeadline   time.Time
	JudgingDeadline      time.Time
}

func (q *Queries) GetSeason(ctx context.Context, id string) (GetSeasonRow, error) {
	row := q.db.QueryRowContext(ctx, getSeason, id)
	var i GetSeasonRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommissionerPlayerID,
		&i.Status,
		&i.SubmissionDeadline,
		&i.JudgingDeadline,
	)
	return i, err
}

const insertSeason = `-- name: InsertSeason :exec
INSERT INTO seasons (id, group_id, commissioner_player_id, status, submission_deadline, judging_deadline)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSeasonParams struct {
	ID                   string
	GroupID              string
	CommissionerPlayerID string
	Status               string
	SubmissionDeadline   time.Time
	JudgingDeadline      time.Time
}

func (q *Queries) InsertSeason(ctx context.Context, arg InsertSeasonParams) error {
	_, err := q.db.ExecContext(ctx, insertSeason,
		arg.ID,
		arg.GroupID,
		arg.CommissionerPlayerID,
		arg.Status,
		arg.SubmissionDeadline,
		arg.JudgingDeadline,
	)
	return err
}

const insertSeasonHistoryEntry = `-- name: InsertSeasonHistoryEntry :exec
INSERT INTO season_history (id, season_id, action, actor_player_id, actor_role, override, from_status, to_status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSeasonHistoryEntryParams struct {
	ID            string
	SeasonID      string
	Action        string
	ActorPlayerID string
	ActorRole     string
	Override      bool
	FromStatus    string
	ToStatus      string
}

func (q *Queries) InsertSeasonHistoryEntry(ctx context.Context, arg InsertSeasonHistoryEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertSeasonHistoryEntry,
		arg.ID,
		arg.SeasonID,
		arg.Action,
		arg.ActorPlayerID,
		arg.ActorRole,
		arg.Override,
		arg.FromStatus,
		arg.ToStatus,
	)
	return err
}

const listSeasonHistoryEntries = `-- name: ListSeasonHistoryEntries :many
SELECT id, season_id, action, actor_player_id, actor_role, override, from_status, to_status
FROM season_history
WHERE season_id = $1
ORDER BY created_at ASC, id ASC
`

type ListSeasonHistoryEntriesRow struct {
	ID            string
	SeasonID      string
	Action        string
	ActorPlayerID string
	ActorRole     string
	Override      bool
	FromStatus    string
	ToStatus      string
}

func (q *Queries) ListSeasonHistoryEntries(ctx context.Context, seasonID string) ([]ListSeasonHistoryEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeasonHistoryEntries, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeasonHistoryEntriesRow
	for rows.Next() {
		var i ListSeasonHistoryEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Action,
			&i.ActorPlayerID,
			&i.ActorRole,
			&i.Override,
			&i.FromStatus,
			&i.ToStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonsForGroup = `-- name: ListSeasonsForGroup :many
SELECT id, status, submission_deadline, judging_deadline
FROM seasons
WHERE group_id = $1
`

type ListSeasonsForGroupRow struct {
	ID                 string
	Status             string
	SubmissionDeadline time.Time
	JudgingDeadline    time.Time
}

func (q *Queries) ListSeasonsForGroup(ctx context.Context, groupID string) ([]ListSeasonsForGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeasonsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeasonsForGroupRow
	for rows.Next() {
		var i ListSeasonsForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.SubmissionDeadline,
			&i.JudgingDeadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeasonStatus = `-- name: UpdateSeasonStatus :exec
UPDATE seasons SET status = $2 WHERE id = $1
`

type UpdateSeasonStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateSeasonStatus(ctx context.Context, arg UpdateSeasonStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSeasonStatus, arg.ID, arg.Status)
	return err
}
