// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stamps.sql

package db

import (
	"context"
)

const getStamp = `-- name: GetStamp :one
SELECT id, stance, label, glyph, copy, created_at
FROM stamps
WHERE id = $1
`

func (q *Queries) GetStamp(ctx context.Context, id string) (Stamp, error) {
	row := q.db.QueryRowContext(ctx, getStamp, id)
	var i Stamp
	err := row.Scan(
		&i.ID,
		&i.Stance,
		&i.Label,
		&i.Glyph,
		&i.Copy,
		&i.CreatedAt,
	)
	return i, err
}

const getStampByStance = `-- name: GetStampByStance :one
SELECT id, stance, label, glyph, copy, created_at
FROM stamps
WHERE stance = $1
`

func (q *Queries) GetStampByStance(ctx context.Context, stance string) (Stamp, error) {
	row := q.db.QueryRowContext(ctx, getStampByStance, stance)
	var i Stamp
	err := row.Scan(
		&i.ID,
		&i.Stance,
		&i.Label,
		&i.Glyph,
		&i.Copy,
		&i.CreatedAt,
	)
	return i, err
}

const listStamps = `-- name: ListStamps :many
SELECT id, stance, label, glyph, copy, created_at
FROM stamps
ORDER BY created_at
`

func (q *Queries) ListStamps(ctx context.Context) ([]Stamp, error) {
	rows, err := q.db.QueryContext(ctx, listStamps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stamp
	for rows.Next() {
		var i Stamp
		if err := rows.Scan(
			&i.ID,
			&i.Stance,
			&i.Label,
			&i.Glyph,
			&i.Copy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
