// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timeframes.sql

package db

import (
	"context"
)

const getRevealTimeframe = `-- name: GetRevealTimeframe :one
SELECT id, label, duration_hours, sort_order, created_at
FROM reveal_timeframes
WHERE id = $1
`

func (q *Queries) GetRevealTimeframe(ctx context.Context, id string) (RevealTimeframe, error) {
	row := q.db.QueryRowContext(ctx, getRevealTimeframe, id)
	var i RevealTimeframe
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.DurationHours,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listRevealTimeframes = `-- name: ListRevealTimeframes :many
SELECT id, label, duration_hours, sort_order, created_at
FROM reveal_timeframes
ORDER BY sort_order
`

func (q *Queries) ListRevealTimeframes(ctx context.Context) ([]RevealTimeframe, error) {
	rows, err := q.db.QueryContext(ctx, listRevealTimeframes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevealTimeframe
	for rows.Next() {
		var i RevealTimeframe
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.DurationHours,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
