     1|/**
     2| * This file was auto-generated by openapi-typescript.
     3| * Do not make direct changes to the file.
     4| */
     5|
     6|export interface paths {
     7|    "/v1/me": {
     8|        parameters: {
     9|            query?: never;
    10|            header?: never;
    11|            path?: never;
    12|            cookie?: never;
    13|        };
    14|        /** Fetch the signed-in Account and Player identity */
    15|        get: operations["getMe"];
    16|        put?: never;
    17|        post?: never;
    18|        delete?: never;
    19|        options?: never;
    20|        head?: never;
    21|        patch?: never;
    22|        trace?: never;
    23|    };
    24|    "/v1/groups": {
    25|        parameters: {
    26|            query?: never;
    27|            header?: never;
    28|            path?: never;
    29|            cookie?: never;
    30|        };
    31|        /** List the signed-in Player's Group Memberships */
    32|        get: operations["listGroups"];
    33|        put?: never;
    34|        /** Create a Group and make the creator a Group Admin */
    35|        post: operations["createGroup"];
    36|        delete?: never;
    37|        options?: never;
    38|        head?: never;
    39|        patch?: never;
    40|        trace?: never;
    41|    };
    42|    "/v1/groups/{groupId}/home": {
    43|        parameters: {
    44|            query?: never;
    45|            header?: never;
    46|            path?: never;
    47|            cookie?: never;
    48|        };
    49|        /** Fetch backend Group home data for a Group member */
    50|        get: operations["getGroupHome"];
    51|        put?: never;
    52|        post?: never;
    53|        delete?: never;
    54|        options?: never;
    55|        head?: never;
    56|        patch?: never;
    57|        trace?: never;
    58|    };
    59|    "/v1/groups/{groupId}/invites": {
    60|        parameters: {
    61|            query?: never;
    62|            header?: never;
    63|            path?: never;
    64|            cookie?: never;
    65|        };
    66|        get?: never;
    67|        put?: never;
    68|        /** Create an Invite for a Group */
    69|        post: operations["createInvite"];
    70|        delete?: never;
    71|        options?: never;
    72|        head?: never;
    73|        patch?: never;
    74|        trace?: never;
    75|    };
    76|    "/v1/invites/{token}/accept": {
    77|        parameters: {
    78|            query?: never;
    79|            header?: never;
    80|            path?: never;
    81|            cookie?: never;
    82|        };
    83|        get?: never;
    84|        put?: never;
    85|        /** Accept an Invite and join its Group */
    86|        post: operations["acceptInvite"];
    87|        delete?: never;
    88|        options?: never;
    89|        head?: never;
    90|        patch?: never;
    91|        trace?: never;
    92|    };
    93|    "/v1/groups/{groupId}/seasons": {
    94|        parameters: {
    95|            query?: never;
    96|            header?: never;
    97|            path?: never;
    98|            cookie?: never;
    99|        };
   100|        get?: never;
   101|        put?: never;
   102|        /** Start a Season for a Group with no active or closing Season */
   103|        post: operations["startSeason"];
   104|        delete?: never;
   105|        options?: never;
   106|        head?: never;
   107|        patch?: never;
   108|        trace?: never;
   109|    };
   110|    "/v1/seasons/{seasonId}/close-submissions": {
   111|        parameters: {
   112|            query?: never;
   113|            header?: never;
   114|            path?: never;
   115|            cookie?: never;
   116|        };
   117|        get?: never;
   118|        put?: never;
   119|        /** Close the Submission Window and move the Season into Judging Grace Period */
   120|        post: operations["closeSeasonSubmissions"];
   121|        delete?: never;
   122|        options?: never;
   123|        head?: never;
   124|        patch?: never;
   125|        trace?: never;
   126|    };
   127|    "/v1/seasons/{seasonId}/finalize": {
   128|        parameters: {
   129|            query?: never;
   130|            header?: never;
   131|            path?: never;
   132|            cookie?: never;
   133|        };
   134|        get?: never;
   135|        put?: never;
   136|        /** Finalize a Season, cap remaining Judging Windows, and lock Standings */
   137|        post: operations["finalizeSeason"];
   138|        delete?: never;
   139|        options?: never;
   140|        head?: never;
   141|        patch?: never;
   142|        trace?: never;
   143|    };
   144|    "/v1/seasons/{seasonId}/history": {
   145|        parameters: {
   146|            query?: never;
   147|            header?: never;
   148|            path?: never;
   149|            cookie?: never;
   150|        };
   151|        /** Fetch visible Season history, including Group Admin override actions */
   152|        get: operations["getSeasonHistory"];
   153|        put?: never;
   154|        post?: never;
   155|        delete?: never;
   156|        options?: never;
   157|        head?: never;
   158|        patch?: never;
   159|        trace?: never;
   160|    };
   161|    "/v1/groups/{groupId}/ideas": {
   162|        parameters: {
   163|            query?: never;
   164|            header?: never;
   165|            path?: never;
   166|            cookie?: never;
   167|        };
   168|        get?: never;
   169|        put?: never;
   170|        /** Create an Idea in exactly one Group */
   171|        post: operations["createIdea"];
   172|        delete?: never;
   173|        options?: never;
   174|        head?: never;
   175|        patch?: never;
   176|        trace?: never;
   177|    };
   178|    "/v1/ideas/{ideaId}/planned-jump": {
   179|        parameters: {
   180|            query?: never;
   181|            header?: never;
   182|            path?: never;
   183|            cookie?: never;
   184|        };
   185|        get?: never;
   186|        put?: never;
   187|        /** Create a Planned Jump from an Idea */
   188|        post: operations["createPlannedJump"];
   189|        delete?: never;
   190|        options?: never;
   191|        head?: never;
   192|        patch?: never;
   193|        trace?: never;
   194|    };
   195|    "/v1/jumps/{jumpId}/evidence-upload-authorizations": {
   196|        parameters: {
   197|            query?: never;
   198|            header?: never;
   199|            path?: never;
   200|            cookie?: never;
   201|        };
   202|        get?: never;
   203|        put?: never;
   204|        /** Authorize direct Evidence upload for a performer's Planned Jump */
   205|        post: operations["authorizeEvidenceUpload"];
   206|        delete?: never;
   207|        options?: never;
   208|        head?: never;
   209|        patch?: never;
   210|        trace?: never;
   211|    };
   212|    "/v1/jumps/{jumpId}/evidence": {
   213|        parameters: {
   214|            query?: never;
   215|            header?: never;
   216|            path?: never;
   217|            cookie?: never;
   218|        };
   219|        get?: never;
   220|        put?: never;
   221|        /** Finalize an Evidence record and transition a Planned Jump into a Performed Jump */
   222|        post: operations["submitEvidence"];
   223|        delete?: never;
   224|        options?: never;
   225|        head?: never;
   226|        patch?: never;
   227|        trace?: never;
   228|    };
   229|    "/v1/jumps/{jumpId}/judgment": {
   230|        parameters: {
   231|            query?: never;
   232|            header?: never;
   233|            path?: never;
   234|            cookie?: never;
   235|        };
   236|        get?: never;
   237|        put?: never;
   238|        /** Submit or edit the signed-in Judge's Judgment for a Performed Jump */
   239|        post: operations["submitJudgment"];
   240|        delete?: never;
   241|        options?: never;
   242|        head?: never;
   243|        patch?: never;
   244|        trace?: never;
   245|    };
   246|    "/v1/jumps/{jumpId}/disputes": {
   247|        parameters: {
   248|            query?: never;
   249|            header?: never;
   250|            path?: never;
   251|            cookie?: never;
   252|        };
   253|        get?: never;
   254|        put?: never;
   255|        /** Raise a Dispute on a visible Jump in the Group */
   256|        post: operations["createDispute"];
   257|        delete?: never;
   258|        options?: never;
   259|        head?: never;
   260|        patch?: never;
   261|        trace?: never;
   262|    };
   263|    "/v1/disputes/{disputeId}/resolution": {
   264|        parameters: {
   265|            query?: never;
   266|            header?: never;
   267|            path?: never;
   268|            cookie?: never;
   269|        };
   270|        get?: never;
   271|        put?: never;
   272|        /** Resolve or override a Dispute with visible Jump outcome changes */
   273|        post: operations["resolveDispute"];
   274|        delete?: never;
   275|        options?: never;
   276|        head?: never;
   277|        patch?: never;
   278|        trace?: never;
   279|    };
   280|}
   281|export type webhooks = Record<string, never>;
   282|export interface components {
   283|    schemas: {
   284|        MeResponse: {
   285|            account: components["schemas"]["Account"];
   286|            player: components["schemas"]["Player"];
   287|        };
   288|        Account: {
   289|            /** @description Internal Account identifier, distinct from Supabase subject. */
   290|            id: string;
   291|            /** Format: email */
   292|            email: string;
   293|        };
   294|        Player: {
   295|            /** @description Internal in-game Player identifier. */
   296|            id: string;
   297|            displayName: string;
   298|        };
   299|        Group: {
   300|            id: string;
   301|            name: string;
   302|        };
   303|        GroupMembership: {
   304|            groupId: string;
   305|            playerId: string;
   306|            /** @enum {string} */
   307|            role: "Group Admin" | "Player";
   308|        };
   309|        Invite: {
   310|            id: string;
   311|            groupId: string;
   312|            token: string;
   313|            createdBy: string;
   314|            /** Format: date-time */
   315|            expiresAt: string;
   316|        };
   317|        Season: {
   318|            id: string;
   319|            groupId: string;
   320|            commissionerPlayerId: string;
   321|            /** @enum {string} */
   322|            status: "Active" | "Judging Grace Period" | "Finalized";
   323|        };
   324|        SeasonHistoryEntry: {
   325|            id: string;
   326|            seasonId: string;
   327|            /** @enum {string} */
   328|            action: "Submissions Closed" | "Season Finalized";
   329|            actorPlayerId: string;
   330|            /** @enum {string} */
   331|            actorRole: "Player" | "Group Admin";
   332|            override: boolean;
   333|            /** @enum {string} */
   334|            fromStatus: "Active" | "Judging Grace Period" | "Finalized";
   335|            /** @enum {string} */
   336|            toStatus: "Active" | "Judging Grace Period" | "Finalized";
   337|            /** Format: date-time */
   338|            createdAt: string;
   339|        };
   340|        SeasonHistoryResponse: {
   341|            entries: components["schemas"]["SeasonHistoryEntry"][];
   342|        };
   343|        Jump: {
   344|            id: string;
   345|            /** @description The exactly one Group this Jump belongs to. */
   346|            groupId: string;
   347|            playerId: string;
   348|            /** @description Present only for Season-linked Planned Jumps. */
   349|            seasonId: string | null;
   350|            /** @enum {string} */
   351|            status: "Idea" | "Planned Jump" | "Performed Jump" | "Judged Jump" | "Unwitnessed Jump" | "Disqualified Jump" | "Removed Jump";
   352|            source: string;
   353|            destination: string;
   354|            food: string;
   355|            offSeason: boolean;
   356|            /** @description Present only after a Season-linked Performed Jump becomes a Judged Jump. */
   357|            finalScore: number | null;
   358|        };
   359|        EvidenceUploadAuthorization: {
   360|            id: string;
   361|            jumpId: string;
   362|            uploadUrl: string;
   363|            /** @enum {string} */
   364|            uploadMethod: "PUT";
   365|            uploadHeaders: {
   366|                [key: string]: string;
   367|            };
   368|            mediaObjectKey: string;
   369|            /** Format: date-time */
   370|            expiresAt: string;
   371|        };
   372|        Evidence: {
   373|            id: string;
   374|            jumpId: string;
   375|            caption: string;
   376|            mediaObjectKey: string;
   377|            /** Format: date-time */
   378|            createdAt: string;
   379|        };
   380|        EvidenceSubmission: {
   381|            jump: components["schemas"]["Jump"];
   382|            evidence: components["schemas"]["Evidence"];
   383|        };
   384|        Judgment: {
   385|            id: string;
   386|            jumpId: string;
   387|            playerId: string;
   388|            commitment: number;
   389|            transgression: number;
   390|            creativity: number;
   391|            presentation: number;
   392|        };
   393|        PerformedJumpView: {
   394|            jump: components["schemas"]["Jump"];
   395|            performer: components["schemas"]["Player"];
   396|            evidence: components["schemas"]["Evidence"];
   397|            disputes: components["schemas"]["Dispute"][];
   398|        };
   399|        Dispute: {
   400|            id: string;
   401|            jumpId: string;
   402|            raisedByPlayerId: string;
   403|            /** @enum {string} */
   404|            concern: "House Rules" | "Credibility" | "Source" | "Destination" | "Food" | "duplicate" | "other";
   405|            details: string;
   406|            /** @enum {string} */
   407|            status: "Open" | "Resolved" | "Overridden";
   408|            resolution?: ("No Action" | "Disqualified Jump" | "Removed Jump") | null;
   409|            resolutionReason?: string | null;
   410|            resolvedByPlayerId?: string | null;
   411|            overrideResolution?: ("Disqualified Jump" | "Removed Jump") | null;
   412|            overrideReason?: string | null;
   413|            overrideByPlayerId?: string | null;
   414|        };
   415|        DisputeResolution: {
   416|            jump: components["schemas"]["Jump"];
   417|            dispute: components["schemas"]["Dispute"];
   418|        };
   419|        StandingEntry: {
   420|            player: components["schemas"]["Player"];
   421|            seasonScore: number;
   422|            judgedJumps: number;
   423|        };
   424|        GroupHomeResponse: {
   425|            group: components["schemas"]["Group"];
   426|            membership: components["schemas"]["GroupMembership"];
   427|            /** @description The Group's currently open Season, including Judging Grace Period, or null when none exists. */
   428|            activeSeason: components["schemas"]["Season"] | null;
   429|            recentJumps: components["schemas"]["PerformedJumpView"][];
   430|            standings: components["schemas"]["StandingEntry"][];
   431|        };
   432|        GroupMembershipSummary: {
   433|            group: components["schemas"]["Group"];
   434|            membership: components["schemas"]["GroupMembership"];
   435|        };
   436|        ListGroupsResponse: {
   437|            memberships: components["schemas"]["GroupMembershipSummary"][];
   438|        };
   439|    };
   440|    responses: never;
   441|    parameters: never;
   442|    requestBodies: never;
   443|    headers: never;
   444|    pathItems: never;
   445|}
   446|export type $defs = Record<string, never>;
   447|export interface operations {
   448|    getMe: {
   449|        parameters: {
   450|            query?: never;
   451|            header?: never;
   452|            path?: never;
   453|            cookie?: never;
   454|        };
   455|        requestBody?: never;
   456|        responses: {
   457|            /** @description The internal Account and Player attached to the external auth identity. */
   458|            200: {
   459|                headers: {
   460|                    [name: string]: unknown;
   461|                };
   462|                content: {
   463|                    "application/json": components["schemas"]["MeResponse"];
   464|                };
   465|            };
   466|            /** @description Missing or invalid bearer token. */
   467|            401: {
   468|                headers: {
   469|                    [name: string]: unknown;
   470|                };
   471|                content?: never;
   472|            };
   473|        };
   474|    };
   475|    listGroups: {
   476|        parameters: {
   477|            query?: never;
   478|            header?: never;
   479|            path?: never;
   480|            cookie?: never;
   481|        };
   482|        requestBody?: never;
   483|        responses: {
   484|            /** @description Group Memberships for the signed-in Player. */
   485|            200: {
   486|                headers: {
   487|                    [name: string]: unknown;
   488|                };
   489|                content: {
   490|                    "application/json": components["schemas"]["ListGroupsResponse"];
   491|                };
   492|            };
   493|            /** @description Missing or invalid bearer token. */
   494|            401: {
   495|                headers: {
   496|                    [name: string]: unknown;
   497|                };
   498|                content?: never;
   499|            };
   500|        };
   501|