/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the signed-in Account and Player identity */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/display-name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the signed-in Player's display name */
        patch: operations["updateDisplayName"];
        trace?: never;
    };
    "/v1/prompt-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the platform-authored prompt catalog (packs and their prompts) */
        get: operations["listPromptCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reveal-timeframes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the available reveal timeframe menu items */
        get: operations["listRevealTimeframes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a new Round for a Community */
        post: operations["startRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rounds/{roundId}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit to an active Round — Player becomes a Jumper */
        post: operations["commitToRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rounds/{roundId}/jumps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jumps for a Round (sealed pre-reveal), with commit/submission counts */
        get: operations["listRoundJumps"];
        put?: never;
        /** Submit a sealed Jump for an active Round */
        post: operations["submitJump"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rounds/{roundId}/jumps/{jumpId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single Jump (sealed pre-reveal for non-author) */
        get: operations["getJump"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rounds/{roundId}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate the reveal condition for a Round and transition to revealed state if condition is met */
        post: operations["evaluateReveal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MeResponse: {
            account: components["schemas"]["Account"];
            player: components["schemas"]["Player"];
        };
        UpdateDisplayNameResponse: {
            player: components["schemas"]["Player"];
        };
        Account: {
            /** @description Internal Account identifier, distinct from external auth provider subject. */
            id: string;
            /** Format: email */
            email: string;
        };
        Player: {
            /** @description Internal in-game Player identifier. */
            id: string;
            displayName: string;
        };
        ErrorResponse: {
            error: string;
            message: string;
        };
        PromptCatalogResponse: {
            packs: components["schemas"]["PromptPack"][];
        };
        PromptPack: {
            id: string;
            displayName: string;
            description: string;
            prompts: components["schemas"]["Prompt"][];
        };
        Prompt: {
            id: string;
            copy: string;
            theme: string;
            costTier: string;
        };
        RevealTimeframe: {
            id: string;
            label: string;
            durationHours: number;
        };
        RevealTimeframesResponse: {
            timeframes: components["schemas"]["RevealTimeframe"][];
        };
        StartRoundRequest: {
            communityId: string;
            /** @description If omitted, a random prompt is selected from the catalog. */
            promptId?: string;
            revealTimeframeId: string;
        };
        Round: {
            id: string;
            communityId: string;
            promptId: string;
            status: string;
            /** Format: date-time */
            revealBy: string;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            prompt?: components["schemas"]["Prompt"];
        };
        StartRoundResponse: {
            round: components["schemas"]["Round"];
        };
        CommitResponse: {
            commitId: string;
        };
        SubmitJumpRequest: {
            caption: string;
            evidenceUrls?: string[];
        };
        SubmitJumpResponse: {
            jump: components["schemas"]["Jump"];
        };
        Jump: {
            id: string;
            roundId: string;
            playerId: string;
            caption?: string;
            evidenceUrls?: string[];
            /** Format: date-time */
            submittedAt: string;
            sealedViewer: boolean;
            playerHasCommitted: boolean;
            playerHasSubmitted: boolean;
        };
        ListJumpsResponse: {
            jumps: components["schemas"]["Jump"][];
            commitCount: number;
            submissionCount: number;
        };
        GetJumpResponse: {
            jump: components["schemas"]["Jump"];
        };
        RevealRoundResponse: {
            round: components["schemas"]["Round"];
            revealed: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The internal Account and Player attached to the external auth identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateDisplayName: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName: string;
                };
            };
        };
        responses: {
            /** @description The updated Player profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateDisplayNameResponse"];
                };
            };
            /** @description Invalid or missing display name. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPromptCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The full prompt catalog, organized by pack. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptCatalogResponse"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRevealTimeframes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The available reveal timeframes, ordered by sort_order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealTimeframesResponse"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startRound: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRoundRequest"];
            };
        };
        responses: {
            /** @description The newly created Round. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRoundResponse"];
                };
            };
            /** @description Invalid or missing request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — e.g. active Round already exists for this Community. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    commitToRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roundId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commit created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — round not found or already committed. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRoundJumps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roundId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of Jumps with commit and submission counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListJumpsResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — round not found. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitJump: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roundId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitJumpRequest"];
            };
        };
        responses: {
            /** @description Jump submitted (sealed until reveal). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitJumpResponse"];
                };
            };
            /** @description Invalid request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — round not found, not committed, or already submitted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getJump: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roundId: string;
                jumpId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Jump (sealed if viewer is not the author and round not revealed). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetJumpResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — jump not found. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    evaluateReveal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roundId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reveal evaluation result. The round field contains current round state; revealed indicates whether the round is in revealed state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealRoundResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — round not found. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
