/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the signed-in Account and Player identity */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in Player's Group Memberships */
        get: operations["listGroups"];
        put?: never;
        /** Create a Group and make the creator a Group Admin */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch backend Group home data for a Group member */
        get: operations["getGroupHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an Invite for a Group */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an Invite and join its Group */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a Season for a Group with no active or closing Season */
        post: operations["startSeason"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{seasonId}/close-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close the Submission Window and move the Season into Judging Grace Period */
        post: operations["closeSeasonSubmissions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{seasonId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize a Season, cap remaining Judging Windows, and lock Standings */
        post: operations["finalizeSeason"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seasons/{seasonId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch visible Season history, including Group Admin override actions */
        get: operations["getSeasonHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/ideas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an Idea in exactly one Group */
        post: operations["createIdea"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ideas/{ideaId}/planned-stunt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Planned Stunt from an Idea */
        post: operations["createPlannedStunt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stunts/{stuntId}/evidence-upload-authorizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authorize direct Evidence upload for a performer's Planned Stunt */
        post: operations["authorizeEvidenceUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stunts/{stuntId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize an Evidence record and transition a Planned Stunt into a Performed Stunt */
        post: operations["submitEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stunts/{stuntId}/judgment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit or edit the signed-in Judge's Judgment for a Performed Stunt */
        post: operations["submitJudgment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stunts/{stuntId}/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Raise a Dispute on a visible Stunt in the Group */
        post: operations["createDispute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/disputes/{disputeId}/resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve or override a Dispute with visible Stunt outcome changes */
        post: operations["resolveDispute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MeResponse: {
            account: components["schemas"]["Account"];
            player: components["schemas"]["Player"];
        };
        Account: {
            /** @description Internal Account identifier, distinct from Supabase subject. */
            id: string;
            /** Format: email */
            email: string;
        };
        Player: {
            /** @description Internal in-game Player identifier. */
            id: string;
            displayName_test?: string;
        };
        Group: {
            id: string;
            name: string;
        };
        GroupMembership: {
            groupId: string;
            playerId: string;
            /** @enum {string} */
            role: "Group Admin" | "Player";
        };
        Invite: {
            id: string;
            groupId: string;
            token: string;
            createdBy: string;
            /** Format: date-time */
            expiresAt: string;
        };
        Season: {
            id: string;
            groupId: string;
            commissionerPlayerId: string;
            /** @enum {string} */
            status: "Active" | "Judging Grace Period" | "Finalized";
        };
        SeasonHistoryEntry: {
            id: string;
            seasonId: string;
            /** @enum {string} */
            action: "Submissions Closed" | "Season Finalized";
            actorPlayerId: string;
            /** @enum {string} */
            actorRole: "Player" | "Group Admin";
            override: boolean;
            /** @enum {string} */
            fromStatus: "Active" | "Judging Grace Period" | "Finalized";
            /** @enum {string} */
            toStatus: "Active" | "Judging Grace Period" | "Finalized";
            /** Format: date-time */
            createdAt: string;
        };
        SeasonHistoryResponse: {
            entries: components["schemas"]["SeasonHistoryEntry"][];
        };
        Stunt: {
            id: string;
            /** @description The exactly one Group this Stunt belongs to. */
            groupId: string;
            playerId: string;
            /** @description Present only for Season-linked Planned Stunts. */
            seasonId: string | null;
            /** @enum {string} */
            status: "Idea" | "Planned Stunt" | "Performed Stunt" | "Judged Stunt" | "Unjudged Stunt" | "Disqualified Stunt" | "Removed Stunt";
            source: string;
            destination: string;
            food: string;
            offSeason: boolean;
            /** @description Present only after a Season-linked Performed Stunt becomes a Judged Stunt. */
            finalScore: number | null;
        };
        EvidenceUploadAuthorization: {
            id: string;
            stuntId: string;
            uploadUrl: string;
            /** @enum {string} */
            uploadMethod: "PUT";
            uploadHeaders: {
                [key: string]: string;
            };
            mediaObjectKey: string;
            /** Format: date-time */
            expiresAt: string;
        };
        Evidence: {
            id: string;
            stuntId: string;
            caption: string;
            mediaObjectKey: string;
            /** Format: date-time */
            createdAt: string;
        };
        EvidenceSubmission: {
            stunt: components["schemas"]["Stunt"];
            evidence: components["schemas"]["Evidence"];
        };
        Judgment: {
            id: string;
            stuntId: string;
            playerId: string;
            difficulty: number;
            transgression: number;
            creativity: number;
            documentation: number;
        };
        PerformedStuntView: {
            stunt: components["schemas"]["Stunt"];
            performer: components["schemas"]["Player"];
            evidence: components["schemas"]["Evidence"];
            disputes: components["schemas"]["Dispute"][];
        };
        Dispute: {
            id: string;
            stuntId: string;
            raisedByPlayerId: string;
            /** @enum {string} */
            concern: "House Rules" | "Credibility" | "Source" | "Destination" | "Food" | "duplicate" | "other";
            details: string;
            /** @enum {string} */
            status: "Open" | "Resolved" | "Overridden";
            resolution?: ("No Action" | "Disqualified Stunt" | "Removed Stunt") | null;
            resolutionReason?: string | null;
            resolvedByPlayerId?: string | null;
            overrideResolution?: ("Disqualified Stunt" | "Removed Stunt") | null;
            overrideReason?: string | null;
            overrideByPlayerId?: string | null;
        };
        DisputeResolution: {
            stunt: components["schemas"]["Stunt"];
            dispute: components["schemas"]["Dispute"];
        };
        StandingEntry: {
            player: components["schemas"]["Player"];
            seasonScore: number;
            judgedStunts: number;
        };
        GroupHomeResponse: {
            group: components["schemas"]["Group"];
            membership: components["schemas"]["GroupMembership"];
            /** @description The Group's currently open Season, including Judging Grace Period, or null when none exists. */
            activeSeason: components["schemas"]["Season"] | null;
            recentStunts: components["schemas"]["PerformedStuntView"][];
            standings: components["schemas"]["StandingEntry"][];
        };
        GroupMembershipSummary: {
            group: components["schemas"]["Group"];
            membership: components["schemas"]["GroupMembership"];
        };
        ListGroupsResponse: {
            memberships: components["schemas"]["GroupMembershipSummary"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The internal Account and Player attached to the external auth identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group Memberships for the signed-in Player. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListGroupsResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description The created Group home. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupHomeResponse"];
                };
            };
            /** @description Invalid Group creation request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGroupHome: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group identity, the Player's Group Membership, current Season state, recent Stunts, and Standings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupHomeResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player does not have a Group Membership for this Group. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite that another signed-in Account can accept. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player does not have a Group Membership for this Group. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invited Group home after the signed-in Player joins. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupHomeResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invite is invalid. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invite was already used, or the signed-in Player already has a Group Membership. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invite expired. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startSeason: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Group home after starting the Active Season. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupHomeResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player does not have a Group Membership for this Group. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The Group already has an active or closing Season. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    closeSeasonSubmissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seasonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Group home after the Season moves into Judging Grace Period. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupHomeResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player is not the Season Commissioner or a Group Admin override actor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Season not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finalizeSeason: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seasonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Group home after the Season is finalized. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupHomeResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player is not the Season Commissioner or a Group Admin override actor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Season not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSeasonHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seasonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit-style Season history entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonHistoryResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player does not have a Group Membership for this Season's Group. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Season not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createIdea: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    source: string;
                    destination: string;
                    food: string;
                };
            };
        };
        responses: {
            /** @description The created Group-scoped Idea. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stunt"];
                };
            };
            /** @description Invalid Idea creation request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player does not have a Group Membership for this Group. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createPlannedStunt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ideaId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description When true, the Planned Stunt is explicitly Off-Season even during an Active Season. */
                    offSeason?: boolean;
                };
            };
        };
        responses: {
            /** @description The Planned Stunt, Season-linked by default during an Active Season. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stunt"];
                };
            };
            /** @description Invalid Planned Stunt request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player is not allowed to plan this Idea. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Idea not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authorizeEvidenceUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stuntId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    contentType: string;
                };
            };
        };
        responses: {
            /** @description Direct upload target and authorization metadata for the Evidence media. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceUploadAuthorization"];
                };
            };
            /** @description Invalid Evidence upload authorization request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player is not the performer of this Planned Stunt. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Planned Stunt not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stuntId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    uploadAuthorizationId: string;
                    caption: string;
                };
            };
        };
        responses: {
            /** @description Backend-owned Evidence record and the updated Performed Stunt. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceSubmission"];
                };
            };
            /** @description Invalid Evidence submission request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player is not the performer of this Planned Stunt. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Planned Stunt or upload authorization not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitJudgment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stuntId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    difficulty: number;
                    transgression: number;
                    creativity: number;
                    documentation: number;
                };
            };
        };
        responses: {
            /** @description The edited Judgment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Judgment"];
                };
            };
            /** @description The created Judgment. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Judgment"];
                };
            };
            /** @description Invalid Judgment request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player is not an eligible Judge for this Performed Stunt. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Performed Stunt not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The Judging Window is closed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createDispute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stuntId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    concern: "House Rules" | "Credibility" | "Source" | "Destination" | "Food" | "duplicate" | "other";
                    details: string;
                };
            };
        };
        responses: {
            /** @description The created Dispute. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dispute"];
                };
            };
            /** @description Invalid Dispute request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player does not have a Group Membership for this Group. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Visible Stunt not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resolveDispute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disputeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    resolution: "No Action" | "Disqualified Stunt" | "Removed Stunt";
                    resolutionReason: string;
                };
            };
        };
        responses: {
            /** @description The updated Stunt and Dispute resolution state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeResolution"];
                };
            };
            /** @description Invalid Dispute resolution request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signed-in Player is not an authorized resolver for this Dispute. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dispute not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
